parameters: 
  signStep: []
    
steps:
- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))

- script: nbgv cloud -p Ix.NET\Source
  displayName: Set Version
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))
  
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.400-preview-009171'

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: Ix.NET/Source/**/System.Interactive*.csproj;!Ix.NET/Source/**/*.Tests*.csproj;!Ix.NET/Source/refs/**
    configuration: $(BuildConfiguration)
    packDirectory: $(Build.ArtifactStagingDirectory)\artifacts    
    verbosityPack: Minimal
  displayName: Pack

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: Ix.NET/Source/**/*.Tests.csproj
    arguments: -c $(BuildConfiguration) --collect:"Code Coverage" -s $(System.DefaultWorkingDirectory)/Ix.NET/Source/CodeCoverage.runsettings /p:DebugType=Full 
  displayName: Run Tests
  
- ${{ parameters.signStep }}

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)\artifacts
    ArtifactName: artifacts
    publishLocation: Container
  condition: eq(variables['system.pullrequest.isfork'], false)